image: privacybydesign/debian:latest

stages:
  - build

before_script:
  - set -euxo pipefail

site:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - ./*
  script:
    - rm .gitlab-ci.yml
    - rm -rf .git
